services:
  postgis:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: grocerytracker
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgis_data:
